### ISSUE TITLE
XP12 animation problem

### ISSUE THREAD

**Issue by marcelwirtz** [omx5o/JoinFS#3]
Hello,
a friend of mine and me using JoinFS on XP12. For the most things ist works awesome but we experience some bugs on the airplane model or animations.

Yesterday for example we both took the Beechcraft Baron 58 and had the same model selected in JoinFS but then we got the landing gear spinning around the airplane while the engine is running and the passenger door was located above the airplane.

I would try to fix it my self but i cant figure out if it is a problem with the XP plugin and the injection of the other airplanes or just something with the DATAREF synchronisation.

Hope you can give me a short hint so i can take a look into this.
Thanks!

**Comment by omx5o** [comment]
Hi,

It's a long time since I looked at any of this, but I think the plugin code
is the best place to look. I can't remember if datarefs solely controlled
the animations. It may be worth looking at the latest X-Plane SDK to see if
they have any new methods for drawing plane objects. I seem to remember
that just trying to draw the objects from the files wasn't quite good
enough to have everything working, but at the time the SDK lacked the
ability to draw an aircraft object using the SDK. It only supported adding
"AI" aircraft, but that had some other issues associated with it. In the
plugin code I think you might be able to see there is some code for both
methods, one of which might be commented out. There's not much code in the
JoinFS plugin so it should be fairly easy to work out.

Peter

**Comment by marcelwirtz** [comment]
Thank you for the reply. Maybe i only have to update the XPMP2 which is compatible with XP12. I will take a look into it and work it out.

**Comment by marcelwirtz** [comment]
Just to share a quick fix, which seemed to work properly with XP12. The generation of the CSL files is the problem.

In file XPlane.cs:1591 there is a calculation for the y and z axis for the new OBJ file of the CSL. If i remove the calculation the models ingame seem to be build correctly. Some aircrafts are a bit to low and stuck in the ground but the general problem is fixed with this.

```c++
// modify position
x += objX;
y += objY;
z += objZ;
//y += objY - cogY;
//z += objZ - cogZ;
```
